# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/ghaudit:pull_request
claim_pattern:
  workflow_ref: chainguard-dev/ghaudit/\.github/workflows/presubmit-testing\.yaml@.* # TODO(mattmoor): change this back to refs/heads/main (for PRT)

# This is running untrusted code in a public repository as pull_request_target.
# Seek a security review before changing these permissions.
permissions:
  metadata: read
  administration: read
