# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: e2e presubmit test

on:
  pull_request_target:
    branches: ["main"]

permissions: {}

jobs:
  e2e-presubmit-test:
    runs-on: ubuntu-latest

    # This is running untrusted code in a public repository as pull_request_target.
    # Seek a security review before changing any aspect of this workflow.
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: './go.mod'
        check-latest: true

    - uses: chainguard-dev/octo-sts-action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
      id: octo-sts
      with:
        scope: ${{ github.repository }}
        identity: presubmit-testing

    - name: Check default permissions
      env:
        GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        go run . repo \
          --organization "${GITHUB_REPOSITORY_OWNER}" \
          --repository "${REPO_NAME}" \
          default-permissions

    - name: Check for deploy keys
      env:
        GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        go run . repo \
          --organization "${GITHUB_REPOSITORY_OWNER}" \
          --repository "${REPO_NAME}" \
          deploy-keys

    - name: Check branch protections
      env:
        GH_TOKEN: ${{ steps.octo-sts.outputs.token }}
        REPO_NAME: ${{ github.event.repository.name }}
      run: |
        go run . repo \
          --organization "${GITHUB_REPOSITORY_OWNER}" \
          --repository "${REPO_NAME}" \
          branch-protections
